#!/usr/bin/perl -w -s
# Sane XKB configuration tool.
# (c)2020 OHIR RIPE. Dual licensed under MIT and GPLv3.
#
# This script is meant to be used once a decade or so. It does use globals,
# copy code, mutate global data in subs, and it keeps flow mostly linear.
# I do not see merit in engineering this script to be easy maintainable as
# XKB itself is so stable that its maintainers still refuse to merge
# spec-fixing patches used by downstream for decades now ().
# TODO
# [x] list current layout to the terminal
# [ ] prepare (init) sane maps using current layout
# [ ] generate XKB files from the maps
use v5.26.1; ### UCD v6. There is no sense in using older perls for this script.
use utf8; use integer;
# check unicode status
unless($ENV{PERL_UNICODE} and $ENV{PERL_UNICODE}=~/^(?:[SDA]{3}|IOEioA)$/){
die<<DOE
Unicode environment is not properly configured.
run as: PERL_UNICODE=SDA $0 [options]
        Alternatively add below line to your .bashrc or .zshrc:
 export PERL_UNICODE=SDA
DOE
}
### Bad (obsolete) ucd corrections:  OS/version dependent!
my $W="🦓";   # put your out-of-ucd table wide glyphs here
my $O="⎇☁☎☏"; # put your right-overflowing glyphs here. Overflow happens
              # when ucd used by display device has got width wrong.

### default dirs and files
our $xkbdir or $xkbdir = '/usr/share/X11/xkb';
our $cnfdir or $cnfdir = "$ENV{HOME}/.xkb/sane";
our $xkdata or $xkdata ='./xkbs-data';# testing, hacking
sub usage { die shift||<<DOE
  Usage: $0 [options] command arg, arg file[.skd]

    commands:
      -show      print layout for gears: 1/2 3/4 5/6
                 Default if command runs as "kblayout"
      -mknew [=filename.skd] ### not implemented yet ##
                 make stub layout file in current empty directory

    options:
      -h        this help
      -v        be verbose
      -g7       show for gears: 1/2 7/8 9/10
      -num      show edit and numeric block layout 
      -ansi     use ansi terminal codes for output (dead keys mostly)
      -wide=ch  Correct display for a wide character(s) given.
      -ovfl=ch  Correct display for a overflowing character(s) given.

      ########### Generators are not implemented yet! #######################
      -legacy   generate for systems with none or poor UTF8 locale support
                This will produce tables using latinX keysyms (where normally
                sane tables would use utf for all but ascii symbols).
                Note that you can not edit .xkbs source on legacy systems,
                as old "codepage/latinX" symbols in the source would not
                be properly recognized.

      -xkbdir=$xkbdir # xkb system dir
      -cnfdir=$cnfdir # user definitions dir
DOE
;}
our $ovfl; $ovfl and $ovfl=~/[^A-Za-z0-9]+/ and $O.=$ovfl, say "Overflows: $O";
our $wide; $wide and $wide=~/[^A-Za-z0-9]+/ and $W.=$wide, say "Wide: $W";
# below opts for someone who knows what she's doing
#    -xkdata           // dev data, keysyms and other constant stuff
#    -pcgeom=pc105     // keyboard type: pc104|pc105
#    -driver=evdev     // some still use xfree86
#    -extras=inet      // xkb default for evdev driver
#    list              // command: flat
our $h and usage; our ($v); # help, verbose
our $driver or $driver = 'evdev';     # some still use xfree86
our $pcgeom or $pcgeom = 'pc105';     # default is the best
our $extras or $extras = 'inet';      # media keys etc
our $ansi;  my ($invb,$inve)=("\x1b[7m","\x1b[0m");
our $g7;    my @SG=$g7?(1,2,7,8,9,10):(1,2,3,4,5,6);
our($list, $show, $num);
my (%def, %outstr, %byU, $fh, $footer); $footer='';
my $legendtab=10;  # console output
my $legendmax=115; # console min width is 116 anyway

sub initmaps; sub rdata; sub repr; sub alnum;
sub showcurr; sub listwhat;

### main ###
initmaps;
if($0=~/kblayout$/ or $show){ # print layout to the terminal
    my $w=$num?'consnum':'console'; print alnum($w),legend();
    $footer and print $footer;
    exit 0;
}
$list and listwhat($list), exit 1;    # Print linear list (layout debug helper).

### subs
sub alnum { my ($g,$r,$i)=@{$outstr{$_[0]}};
    return $def{$g}=~s/$i/$r->(\%+)/mrego; }
sub legend { my $lead; my $max=$legendtab;
  for(qw/0 1/){ my $i=-1; my $ll=0; my $p=$_;
  for(@{$def{legend}}) { $i++; $_ or next;
    my $g=$_; my $ou="G$i:"; $lead++ or print
    "-----¦  Short descriptions:  ¦".('-' x ($legendmax-30))."\n";
    for(@{$g}){
      $ll>$legendmax-$max and $ll=0,$ou.="\n   ";
      my $u="  ¦$_"; my $ul=length($u);
      $p or $max=($max<$ul?$ul:$max),next;
      $u.=' ' x ($max-$ul); $ll+=length($u); $ou.=$u;
    } $p and print "$ou\n"; $ll=0;
  }}
}

# TODO transformations for .json .glade .html
sub termo { my $m=shift;
    my ($a,$r,$d,$t,$c,$sh,$o,@g)=
       ($m->{a},$m->{r},$m->{d},$m->{t},$m->{c},0,' ');
    my @R=@{$def{repr}{$c}}; @R or return $a; unshift @R, '!';
    $t=~/^[A-I]/ and $sh=1; $o=($d=~/[│┃]/)?$d:' ';
    for(@SG){ $_%2==$sh and next; push @g,$_}
    if($c==65){ # space is special
      for(@g){
        my $x=$R[$_]||'    '; my $sl=length($x);
        $sl<4 and $x.=(' ' x (4-$sl)); $sl>4 and $x=substr($x,0,4);
        $o.=chr(0x24f4+$_)." $x  ";
      } chop($o);
      return $o;
    }# space
    if($t eq 'A'){ # gear (control) keys are special too
      my $x=$R[1]||'    '; my $sl=length($x); my $pl=$sl;
      for($x){ $sl-=()=/\p{Mn}|\p{Me}/g; $sl+=()=/\p{Dt=Wide}|\p{Ea=W}/g; }
      $sl<4 and $x.=(' ' x (4-$sl)); $sl>4 and $x=substr($x,0,4);
      return "$o$x ";
    }
    for(@g){
      my $g=$_; my $x=$R[$_]||'';
      $x=~s/\s+//gaa; my $l=length($x);
      $x or $o.='  ', next; my $i;
      for($x){
        # if($i=$def{custkeys}{$x}){ last } # forced representation by input symbol
        if($l==1){ # singles
          $g<3 and $x=~/^[0-9A-Z]/aa  and chop($o), $i="$x\x{20de}  ", last;
          $x=~/^\p{Dt=Wide}|\p{Ea=W}/ and chop($o), $i="$x ", last; # fallback;
          index($O,$x)>=0 and chop($o), $i="$x  ", last; # correct for obsolete ncb
          $i="$x ", last;
        }
        elsif($l==2){ $i="$x "; $x=~/\p{Mn}|\p{Me}/ or chop($o); last; } # doubles
        elsif($x=~/^%([nwuFsc.])(.+)/){ # repr that differs from input symbolic
          # %n:asis %w:wide %u:uwide %F:Fn %s:square %c:circle %.:dead
          $1 eq 'n' and           $i="$2 ", last;
          $1 eq 'w' and chop($o), $i="$2 ", last;
          $1 eq 'u' and chop($o), $i="$2  ", last;
          $1 eq 'F' and $g<3 and chop($o), chop($o), $i="F".chr(0x2487+$2)." ", last;
          $1 eq 'f' and $i=chr(0x2487+$2)."\x{1DEB} ", last; # Fx at higher gears
          $1 eq 's' and $i="$2\x{20de} ", last;
          $1 eq 'c' and $i="$2\x{20dd} ", last;
          $1 eq '.' and $ansi and $i="$invb$2$inve ", last;
          $1 eq '.' and $i="$2\x{20e0} ", last;
          $i="$1\x{20e0} "; # bad letter
        }
        # make verbose legend for any other. Use ₀⃧ ... ₘ⃧᷵ markers.
        my $leg=$def{legnum}{$g}||0;$def{legnum}{$g}=$leg+1;
        my $xt=$leg>22?chr(0x1de6+$leg/10):''; # 240 markers per gear - enough.
        $i=($leg>9?chr(0x2090+(12-$leg%13)):chr(0x2080+$leg%10))."\x{20e7}$xt ";
        my $xx=$x.((length($x)<5)?' ' x (4-length($x)):''); # inner justify
        push @{$def{legend}[$g]},"$i$xx  ".@{$def{name}{$c}}[$g-1];
      } # for $x
      $o.=$i;
    } # for @g
    chop($o);
    return $o;
}

# get current kb layout, init transformations dict
sub initmaps {
  rdata; if(open(my $fh, "<",$xkdata)){ rdata $fh } # prepare data
  my (undef, $x)=split / /,`stty size`; chomp($x);
  ($? or $x=~/[^0-9]/) and usage "Install stty first!\n";
  $x<$legendmax and $footer.="\nToo narrow terminal (<$legendmax). Pipe output to |less -S.\n";
  $x=`xmodmap -pk`; $? and usage "Install xmodmap first!\n";
  for(split /^/, $x) { chomp;
    s/^\s*(\d+)\s+// or next; my $kn=$1; /0x/ or next;
    my ($i, $v, @ko); my @kl=split;
    my $h = $def{'khex'}{$kn}||[];
    my $n = $def{'name'}{$kn}||[];
    my $r = $def{'repr'}{$kn}||[];
    for($i=0;$i<20;$i++){ $v=$kl[$i];
        $v or $v=$i%2?'  ':'0x1000';
        push @ko, $v=~s/[()]//gr;
    }
    $ko[0] eq $ko[4] and $ko[4]=$ko[6]='0x1000',$ko[5]=$ko[7]='  ';
    $i=0; splice @ko,16,4,splice @ko,4,4; # mod2 => g9
    for(@ko){ $i++%2 and push(@$n,$_), next; push(@$h,$_); push(@$r,repr($_)); }
    $def{'name'}{$kn}=$n; $def{'khex'}{$kn}=$h; $def{'repr'}{$kn}=$r;
  }
  my $termre=qr/(?<a>(?<r>(?<d>\S) +(?<t>[A-Ia-i])_{0,2}(?<c>\d{1,3})))/m;
  %outstr=( # keep all outstream transformations in one place
    'console',[ 'pc105', \&termo, $termre],
    'consnum',[ 'pcnum', \&termo, $termre],
    ); 
  $def{'repr'}{'999'}=[qw(⓵ ⓶ ⓷ ⓸ ⓹ ⓺ ⓻ ⓼ ⓽ ⓾)];
}

sub listwhat {
    my $pr=shift||1; $pr eq 'flat' and $pr = 1;
    for($pr){
    /1/ and do {
      for (sort{$a<=>$b}(keys(%{$def{'name'}}))) {
        print "$_ name => " . join(', ',    @{$def{'name'}{$_}})."\n";
        print "$_ khex => " . join(', ',    @{$def{'khex'}{$_}})."\n";
        print "$_ repr => │ " . join(' │ ', @{$def{'repr'}{$_}})." │\n\n";
      } };
    }
}
# repr normal, ascii->ascii, any other keysym goes U
sub repr { # takes keysym hex, returns .skd representation string.
    my $in=shift; my $o;
    for($in) {
        /^0x1000$/       and return '  ';
        /^0x0000$/       and $o='␥⃥',last;
        /^(0x....)$/     and $o=$def{'sym'}{$1}[4] and last; # sname => outrepr, xxxx
        /^(0x....)$/     and $o=$def{'sym'}{$1}[1] and last; # sname => inrepr, xxxx
        /^0x00([0-7].)$/ and $o =chr(oct($_)),last; # ascii, in case of broken data
        /^0x(....)$/     and $o=$1,last;            # unknowns go by hex number
        /^0x1008ff(..)$/ and $o ="xF$1",last;       # XFree86 FF
        /^0x1008fe(..)$/ and $o ="xE$1",last;       # XFree86 FE
        /^0xffffffff$/   and $o='␥',last;           # Void symbol
        /(0x10([012345]....))$/ and $o=$def{'uni'}{$1}[1] and last;
        #$2 or print("$_ unknown \$2!\n"), $o='*⃜', last;
        $2 or $o='*⃜', last; # unknown key
        $o=chr(oct("0x$2")); last;
        if(/(0x10([0123]....))$/){ # unicode
            my $cs="0x$2"; my $cp=oct($cs); my $c=chr($cp);
            $o=$def{'uni'}{$1}[1]||chr($cp); # chr(oct("0x$2"));
            last;
        } die "Should not happen!\n";
    }
    for($o){ # n:asis wide uwide Fn square circle .dead
      s/\s+//gaa;
      /^%[nwuFsc.]/ and return $o; # manual set
      /^\.(\X)/ and return "%.$1"; # deads
      /^\#?F(\d{1,2})/aa and return "%F$1"; # funcs
      /^\p{Mn}|^\p{Me}/ and return "◌$o";
      /^\p{Mc}/        and return "%w◌$o";
      /^\p{Dt=Wide}|\p{Ea=W}/ and return "%w$o";
      index($W,$o)>=0 and return "%w$o";
      return $o;
    }
}
sub rdata {
  my ($c, $u, $k, $t);
  my $fh=shift||"main::DATA";
  while(<$fh>) {
    /^:\s/maa and next; # : comments allowed; double to escape a colon
    if(m'^:(\w):(\w+):\s'maa){
        $c and $def{$k}=$c; $t=$1; $k=$2;
        $t=~m'[sS]' and $c=$def{$k}||'', next;
        $t=~m'[UH]' and $c=$def{$k}||{}, next;
        $t=~m'[tT]' and $c=$def{$k}||[], next;
        $c=undef; print STDERR "Bad section :$t:$k: in line $.. Skipping.\n";
        next;
    } defined $c or next; /^::/ and s/^::/:/; # fix data line with escaped comment char
    if($t eq 'S'){ $c.=$_; next } chomp;
    if($t eq 'T'){ push @$c, $_; next; }
    if($t eq 'H'){ /^(\w+)\s/aa  and @{$c->{$1}}=split, shift @{$c->{$1}}; next; }
    if($t eq 'U'){ /^(0x[0-9a-f]+)\s/aa or next;
        my @e=split; $c->{$1}=\@e; $byU{$e[2]}=\@e; next }
    print STDERR "Type $t of :$t:$k: line $. is not supported!\n";
  }
  $k and $def{$k}=$c;
  close $fh;
}
sub mklayout { -d "$xkbdir/rules" or usage
    "Wrong XKB path: directory $xkbdir not found!\n"; }
__END__
:S:pcnum:
   ┌───────┬───────┬───────┐    ┌───────┬───────┬───────┬───────┐
   │⌂ G118 │⬉ G110 │▀ G112 │    │ NumLk │/ G106 │* G_63 │- G_82 │
   │⌂ g118 │⬉ g110 │▀ g112 │    │       │/ g106 │* g_63 │- g_82 │
   ├───────┼───────┼───────┤    ├───────┼───────┼───────┼───────┤
   │⌧ G119 │⬊ G115 │▄ G117 │    │⬉ G_79 │▲ G_80 │▀ G_81 │+ G_86 │
   │⌧ g119 │⬊ g115 │▄ g117 │    │7 g_79 │8 g_80 │9 g_81 │+ g_86 │
   └───────┴───────┴───────┘    ├───────┼───────┼───────┤       │
    ➋ I999                      │◀ G_83 │· G_84 │▶ G_85 │+      │
    ➊ i999                      │4 g_83 │5 g_84 │6 g_85 │       │
      ᵍᵉᵃʳ ┌───────┐            ├───────┼───────┼───────┼───────┤
           │△ G111 │            │⬊ G_87 │▼ G_88 │▄ G_89 │E G104 │
           │▲ g111 │            │1 g_87 │2 g_88 │3 g_89 │n g104 │
   ┌───────┼───────┼───────┐    ├───────┴───────┼───────┤t      │
   │◁ G113 │▽ G116 │▷ G114 │    │    0 G_90     │⌧ G_91 │e      │
   │◀ g113 │▼ g116 │▶ g114 │    │    0 g_90     │⌧ g_91 │r      │
   └───────┴───────┴───────┘    └───────────────┴───────┴───────┘
:S:pc105:
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ◀⃞ ▲⃞ ▼⃞ ▶⃞ Cursor, ⌂⃜ Insert, ⌫  Backspace, ⬉⃞ Home, ▀⃞ PgUp, ▄⃞ PgDown, ⬊⃞ End, ⌧ Delete │ Gear chords ⓷▝⓹▝⓽▝, ⓷ +⓹ =⓻ │
├─────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┤
│· F__9   │⒈ F_67 │⒉ F_68 │⒊ F_69 │⒋ F_70 │⒌ F_71 │⒍ F_72 │⒎ F_73 │⒏ F_74 │⒐ F_75 │⒑ F_76 │⒒ F_95 │⒓ F_96 │Ϫ G119 │
│· f__9   │⒈ f_67 │⒉ f_68 │⒊ f_69 │⒋ f_70 │⒌ f_71 │⒍ f_72 │⒎ f_73 │⒏ f_74 │⒐ f_75 │⒑ f_76 │⒒ f_95 │⒓ f_96 │ϫ g119 │
├───────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴─────┬─┴───────┤
│~ E_49 │! E_10 │@ E_11 │# E_12 │$ E_13 │% E_14 │^ E_15 │& E_16 │* E_17 │( E_18 │) E_19 │_ E_20 │+ E_21 │⇏ E_22   │
│` e_49 │1 e_10 │2 e_11 │3 e_12 │4 e_13 │5 e_14 │6 e_15 │7 e_16 │8 e_17 │9 e_18 │0 e_19 │- e_20 │= e_21 │⇍ e_22   │
├───────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬───────┤
│ ⇤ D_23  │Q D_24 │W D_25 │E D_26 │d D_27 │T D_28 │Y D_29 │U D_30 │I D_31 │O D_32 │P D_33 │{ D_34 │} D_35 │| D_51 │
│ ⇥ d_23  │q d_24 │w d_25 │e d_26 │r d_27 │t d_28 │y d_29 │u d_30 │i d_31 │o d_32 │p d_33 │[ d_34 │] d_35 │\ d_51 │
├─────────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴──┬────┴───────┤
│ c̶ₐ̶ₚ̶ₛ̶· C_66 │A C_38 │S C_39 │D C_40 │F C_41 │G C_42 │H C_43 │J C_44 │K C_45 │C C_46 │: C_47 │" C_48 │ ↵  · C_36  │
│ Gear· c_66 │a c_38 │s c_39 │d c_40 │f c_41 │g c_42 │h c_43 │j c_44 │k c_45 │l c_46 │; c_47 │' c_48 │ENT · c_36  │
├──────┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─────┴─┬─┏━━━━━━━┓┘
│ ²cₐₚₛ│≤ B_94 │Z B_52 │X B_53 │C B_54 │V B_55 │B B_56 │N B_57 │M B_58 │< B_59 │> B_60 │? B_61 │ ²cₐₚₛ │ ┃△ G111 ┃
│Shift▝│≥ b_94 │z b_52 │x b_53 │c b_54 │v b_55 │b b_56 │n b_57 │m b_58 │, b_59 │. b_60 │/ b_61 │ Shift▝│ ┃▲ g111 ┃
├─────┬┴────┬──┴──┬────┴───────┴───────┴───────┴─────┬─┴───┬───┴─┬─────┼─────┬─┴───────┴──┲━━━━┷━━┯━━━━┷━┹┬──────┺┓
│ A_37│ A133│ A_64│         ·                   H_65 │ A108│ A134│ A135│ A105│  ➋ I999    ┃◁ G113 │▽ G116 │▷ G114 ┃
│Ctrl │Win  │Alt  │Space    ·                   h_65 │Alt  │Win  │Menu │Ctrl │  ➊ i999    ┃◀ g113 │▼ g116 │▶ g114 ┃
└─────┴─────┴─────┴──────────────────────────────────┴─────┴─────┴─────┴─────┘    ᵍᵉᵃʳ    ┗━━━━━━━┷━━━━━━━┷━━━━━━━┛
 Options: -g7 shows upper gears   -num shows edit keys and numpad layout   -ansi shows dead keys inverted.
:H:combs: xkb-name conf-symbol overlay-codepoint
comb_aboveoverline        .◌̅   0305
comb_dblabverticalline    .◌̎   030E
comb_candrabindu          .◌̐   0310
comb_aboveturnedcomma     .◌̒   0312
comb_abovecommaright      .◌̕   0315
comb_belowgrave           .◌̖   0316
comb_belowacute           .◌̗   0317
comb_belowcaron           .◌̬   032C
comb_belowinvertedbreve   .◌̯   032F
:H:deads: repr overlay keysym xkb-name overlay-codepoint
.à 0300 0xfe50 dead_grave
.á 0301 0xfe51 dead_acute
.â 0302 0xfe52 dead_circumflex
.ã 0303 0xfe53 dead_tilde
.ā 0304 0xfe54 dead_macron
.ă 0306 0xfe55 dead_breve
.ċ 0307 0xfe56 dead_abovedot
.ä 0308 0xfe57 dead_diaeresis
.å 030A 0xfe58 dead_abovering
.ő 030B 0xfe59 dead_doubleacute
.č 030C 0xfe5a dead_caron
.ç 0327 0xfe5b dead_cedilla
.ą 0328 0xfe5c dead_ogonek
.ɩ 0345 0xfe5d dead_iota
.ˬ 032C 0xfe5e dead_voiced_sound
.˲ 0355 0xfe5f dead_semivoiced_sound
.ḅ 0323 0xfe60 dead_belowdot
.ƈ 0309 0xfe61 dead_hook
.ơ 031B 0xfe62 dead_horn
.đ 0335 0xfe63 dead_stroke
.’ 0313 0xfe64 dead_abovecomma
.ʽ 0314 0xfe65 dead_abovereversedcomma
.ȁ 030F 0xfe66 dead_doublegrave
.ḁ 0325 0xfe67 dead_belowring
.ḇ 0331 0xfe68 dead_belowmacron
.ḓ 032D 0xfe69 dead_belowcircumflex
.ḛ 0330 0xfe6a dead_belowtilde
.ḫ 032E 0xfe6b dead_belowbreve
.ṳ 0324 0xfe6c dead_belowdiaeresis
.ȃ 0311 0xfe6d dead_invertedbreve
.ș 0326 0xfe6e dead_belowcomma
.¤⃝ 0000 0xfe6f dead_currency
.ə⃝ 0000 0xfe8a dead_small_schwa
.Ə⃝ 0000 0xfe8b dead_capital_schwa
.Ɛ⃝ 0000 0xfe8c dead_greek
._ 0332 0xfe90 dead_lowline
.ˈ 030D 0xfe91 dead_aboveverticalline
.ˌ 0329 0xfe92 dead_belowverticalline
./ 0338 0xfe93 dead_longsolidusoverlay
:T:inrows:
 =Funcs  ESC    F1   F2   F3   F4   F5   F6   F7   F8   F9   F10  F11  F12  DEL
 =Digit  `   1    2    3    4    5    6    7    8    9    0    -    =    BKSP
 =Tab    TAB  q    w    e    r    t    y    u    i    o    p    [    ]    \
 =Caps   CAPS  a    s    d    f    g    h    j    k    l    ;    '    ENTER
 =Shift  LSGT   z    x    c    v    b    n    m    ,    .    /    SPACE
 =NumPad P0   P1   P2   P3   P4   P5   P6   P7   P8   P9   P/   P*   P-   P+
 =EdMov  P.   PENT INS  HOME END  PGUP PGDN UP   DOWN LEFT RIGHT
:T:innums:
 =Funcs    9    67   68   69   70   71   72   73   74   75   76   95    96  119
 =Digit  49  10  11   12   13   14   15   16   17   18   19   20   21    22
 =Tab     23  24  25   26   27   28   29   30   31   32   33   34   35    51
 =Caps   66    38  39   40   41   42   43   44   45   46   47   48       36
 =Shift :50 94  52  53   54   55   56   57   58   59   60   61  :62      65
 =NumPad P0   P1   P2   P3   P4   P5   P6   P7   P8   P9   P/   P*   P-   P+
 =NumPad P0   P1   P2   P3   P4   P5   P6   P7   P8   P9   P/   P*   P-   P+
 =EdMov  P.   PENT INS  HOME END  PGUP PGDN UP   DOWN LEFT RIGHT
:U:sym:  Made with: ./sxkbutil -mkdata
0x0020 _sp_ 0020 Space
0x0021 !    0021 exclam
0x0022 "    0022 quotedbl
0x0023 #    0023 numbersign
0x0024 $    0024 dollar
0x0025 %    0025 percent
0x0026 &    0026 ampersand
0x0027 '    0027 apostrophe
0x0028 (    0028 parenleft
0x0029 )    0029 parenright
0x002a *    002A asterisk
0x002b +    002B plus
0x002c ,    002C comma
0x002d -    002D minus
0x002e .    002E period
0x002f /    002F slash
0x0030 0    0030 0
0x0031 1    0031 1
0x0032 2    0032 2
0x0033 3    0033 3
0x0034 4    0034 4
0x0035 5    0035 5
0x0036 6    0036 6
0x0037 7    0037 7
0x0038 8    0038 8
0x0039 9    0039 9
0x003a :    003A colon
0x003b ;    003B semicolon
0x003c <    003C less
0x003d =    003D equal
0x003e >    003E greater
0x003f ?    003F question
0x0040 @    0040 at
0x0041 A    0041 A
0x0042 B    0042 B
0x0043 C    0043 C
0x0044 D    0044 D
0x0045 E    0045 E
0x0046 F    0046 F
0x0047 G    0047 G
0x0048 H    0048 H
0x0049 I    0049 I
0x004a J    004A J
0x004b K    004B K
0x004c L    004C L
0x004d M    004D M
0x004e N    004E N
0x004f O    004F O
0x0050 P    0050 P
0x0051 Q    0051 Q
0x0052 R    0052 R
0x0053 S    0053 S
0x0054 T    0054 T
0x0055 U    0055 U
0x0056 V    0056 V
0x0057 W    0057 W
0x0058 X    0058 X
0x0059 Y    0059 Y
0x005a Z    005A Z
0x005b [    005B bracketleft
0x005c \    005C backslash
0x005d ]    005D bracketright
0x005e ^    005E asciicircum
0x005f _    005F underscore
0x0060 `    0060 grave
0x0061 a    0061 a
0x0062 b    0062 b
0x0063 c    0063 c
0x0064 d    0064 d
0x0065 e    0065 e
0x0066 f    0066 f
0x0067 g    0067 g
0x0068 h    0068 h
0x0069 i    0069 i
0x006a j    006A j
0x006b k    006B k
0x006c l    006C l
0x006d m    006D m
0x006e n    006E n
0x006f o    006F o
0x0070 p    0070 p
0x0071 q    0071 q
0x0072 r    0072 r
0x0073 s    0073 s
0x0074 t    0074 t
0x0075 u    0075 u
0x0076 v    0076 v
0x0077 w    0077 w
0x0078 x    0078 x
0x0079 y    0079 y
0x007a z    007A z
0x007b {    007B braceleft
0x007c |    007C bar
0x007d }    007D braceright
0x007e ~    007E asciitilde
0x00a0 NBSP 00A0 nobreakspace
0x00a1 ¡    00A1 exclamdown
0x00a2 ¢    00A2 cent
0x00a3 £    00A3 sterling
0x00a4 ¤    00A4 currency
0x00a5 ¥    00A5 yen
0x00a6 ¦    00A6 brokenbar
0x00a7 §    00A7 section
0x00a8 ¨    00A8 diaeresis
0x00a9 ©    00A9 copyright
0x00aa ª    00AA ordfeminine
0x00ab «    00AB guillemotleft
0x00ac ¬    00AC notsign
0x00ad shy  00AD hyphen
0x00ae ®    00AE registered
0x00af ¯    00AF macron
0x00b0 °    00B0 degree
0x00b1 ±    00B1 plusminus
0x00b2 ²    00B2 twosuperior
0x00b3 ³    00B3 threesuperior
0x00b4 ´    00B4 acute
0x00b5 µ    00B5 mu
0x00b6 ¶    00B6 paragraph
0x00b7 ·    00B7 periodcentered
0x00b8 ¸    00B8 cedilla
0x00b9 ¹    00B9 onesuperior
0x00ba º    00BA masculine
0x00bb »    00BB guillemotright
0x00bc ¼    00BC onequarter
0x00bd ½    00BD onehalf
0x00be ¾    00BE threequarters
0x00bf ¿    00BF questiondown
0x00c0 À    00C0 Agrave
0x00c1 Á    00C1 Aacute
0x00c2 Â    00C2 Acircumflex
0x00c3 Ã    00C3 Atilde
0x00c4 Ä    00C4 Adiaeresis
0x00c5 Å    00C5 Aring
0x00c6 Æ    00C6 AE
0x00c7 Ç    00C7 Ccedilla
0x00c8 È    00C8 Egrave
0x00c9 É    00C9 Eacute
0x00ca Ê    00CA Ecircumflex
0x00cb Ë    00CB Ediaeresis
0x00cc Ì    00CC Igrave
0x00cd Í    00CD Iacute
0x00ce Î    00CE Icircumflex
0x00cf Ï    00CF Idiaeresis
0x00d0 Ð    00D0 ETH
0x00d1 Ñ    00D1 Ntilde
0x00d2 Ò    00D2 Ograve
0x00d3 Ó    00D3 Oacute
0x00d4 Ô    00D4 Ocircumflex
0x00d5 Õ    00D5 Otilde
0x00d6 Ö    00D6 Odiaeresis
0x00d7 ×    00D7 multiply
0x00d8 Ø    00D8 Oslash
0x00d9 Ù    00D9 Ugrave
0x00da Ú    00DA Uacute
0x00db Û    00DB Ucircumflex
0x00dc Ü    00DC Udiaeresis
0x00dd Ý    00DD Yacute
0x00de Þ    00DE THORN
0x00df ß    00DF ssharp
0x00e0 à    00E0 agrave
0x00e1 á    00E1 aacute
0x00e2 â    00E2 acircumflex
0x00e3 ã    00E3 atilde
0x00e4 ä    00E4 adiaeresis
0x00e5 å    00E5 aring
0x00e6 æ    00E6 ae
0x00e7 ç    00E7 ccedilla
0x00e8 è    00E8 egrave
0x00e9 é    00E9 eacute
0x00ea ê    00EA ecircumflex
0x00eb ë    00EB ediaeresis
0x00ec ì    00EC igrave
0x00ed í    00ED iacute
0x00ee î    00EE icircumflex
0x00ef ï    00EF idiaeresis
0x00f0 ð    00F0 eth
0x00f1 ñ    00F1 ntilde
0x00f2 ò    00F2 ograve
0x00f3 ó    00F3 oacute
0x00f4 ô    00F4 ocircumflex
0x00f5 õ    00F5 otilde
0x00f6 ö    00F6 odiaeresis
0x00f7 ÷    00F7 division
0x00f8 ø    00F8 oslash
0x00f9 ù    00F9 ugrave
0x00fa ú    00FA uacute
0x00fb û    00FB ucircumflex
0x00fc ü    00FC udiaeresis
0x00fd ý    00FD yacute
0x00fe þ    00FE thorn
0x00ff ÿ    00FF ydiaeresis
0x01a1 Ą    0104 Aogonek
0x01a2 ˘    02D8 breve
0x01a3 Ł    0141 Lstroke
0x01a5 Ľ    013D Lcaron
0x01a6 Ś    015A Sacute
0x01a9 Š    0160 Scaron
0x01aa Ş    015E Scedilla
0x01ab Ť    0164 Tcaron
0x01ac Ź    0179 Zacute
0x01ae Ž    017D Zcaron
0x01af Ż    017B Zabovedot
0x01b1 ą    0105 aogonek
0x01b2 ˛    02DB ogonek
0x01b3 ł    0142 lstroke
0x01b5 ľ    013E lcaron
0x01b6 ś    015B sacute
0x01b7 ˇ    02C7 caron
0x01b9 š    0161 scaron
0x01ba ş    015F scedilla
0x01bb ť    0165 tcaron
0x01bc ź    017A zacute
0x01bd ˝    02DD doubleacute
0x01be ž    017E zcaron
0x01bf ż    017C zabovedot
0x01c0 Ŕ    0154 Racute
0x01c3 Ă    0102 Abreve
0x01c5 Ĺ    0139 Lacute
0x01c6 Ć    0106 Cacute
0x01c8 Č    010C Ccaron
0x01ca Ę    0118 Eogonek
0x01cc Ě    011A Ecaron
0x01cf Ď    010E Dcaron
0x01d0 Đ    0110 Dstroke
0x01d1 Ń    0143 Nacute
0x01d2 Ň    0147 Ncaron
0x01d5 Ő    0150 Odoubleacute
0x01d8 Ř    0158 Rcaron
0x01d9 Ů    016E Uring
0x01db Ű    0170 Udoubleacute
0x01de Ţ    0162 Tcedilla
0x01e0 ŕ    0155 racute
0x01e3 ă    0103 abreve
0x01e5 ĺ    013A lacute
0x01e6 ć    0107 cacute
0x01e8 č    010D ccaron
0x01ea ę    0119 eogonek
0x01ec ě    011B ecaron
0x01ef ď    010F dcaron
0x01f0 đ    0111 dstroke
0x01f1 ń    0144 nacute
0x01f2 ň    0148 ncaron
0x01f5 ő    0151 odoubleacute
0x01f8 ř    0159 rcaron
0x01f9 ů    016F uring
0x01fb ű    0171 udoubleacute
0x01fe ţ    0163 tcedilla
0x01ff ˙    02D9 abovedot
0x02a1 Ħ    0126 Hstroke
0x02a6 Ĥ    0124 Hcircumflex
0x02a9 İ    0130 Iabovedot
0x02ab Ğ    011E Gbreve
0x02ac Ĵ    0134 Jcircumflex
0x02b1 ħ    0127 hstroke
0x02b6 ĥ    0125 hcircumflex
0x02b9 ı    0131 idotless
0x02bb ğ    011F gbreve
0x02bc ĵ    0135 jcircumflex
0x02c5 Ċ    010A Cabovedot
0x02c6 Ĉ    0108 Ccircumflex
0x02d5 Ġ    0120 Gabovedot
0x02d8 Ĝ    011C Gcircumflex
0x02dd Ŭ    016C Ubreve
0x02de Ŝ    015C Scircumflex
0x02e5 ċ    010B cabovedot
0x02e6 ĉ    0109 ccircumflex
0x02f5 ġ    0121 gabovedot
0x02f8 ĝ    011D gcircumflex
0x02fd ŭ    016D ubreve
0x02fe ŝ    015D scircumflex
0x03a2 ĸ    0138 kra
0x03a3 Ŗ    0156 Rcedilla
0x03a5 Ĩ    0128 Itilde
0x03a6 Ļ    013B Lcedilla
0x03aa Ē    0112 Emacron
0x03ab Ģ    0122 Gcedilla
0x03ac Ŧ    0166 Tslash
0x03b3 ŗ    0157 rcedilla
0x03b5 ĩ    0129 itilde
0x03b6 ļ    013C lcedilla
0x03ba ē    0113 emacron
0x03bb ģ    0123 gcedilla
0x03bc ŧ    0167 tslash
0x03bd Ŋ    014A ENG
0x03bf ŋ    014B eng
0x03c0 Ā    0100 Amacron
0x03c7 Į    012E Iogonek
0x03cc Ė    0116 Eabovedot
0x03cf Ī    012A Imacron
0x03d1 Ņ    0145 Ncedilla
0x03d2 Ō    014C Omacron
0x03d3 Ķ    0136 Kcedilla
0x03d9 Ų    0172 Uogonek
0x03dd Ũ    0168 Utilde
0x03de Ū    016A Umacron
0x03e0 ā    0101 amacron
0x03e7 į    012F iogonek
0x03ec ė    0117 eabovedot
0x03ef ī    012B imacron
0x03f1 ņ    0146 ncedilla
0x03f2 ō    014D omacron
0x03f3 ķ    0137 kcedilla
0x03f9 ų    0173 uogonek
0x03fd ũ    0169 utilde
0x03fe ū    016B umacron
0x047e ‾    203E overline
0x04a1 。   3002 kana_fullstop
0x04a2 「   300C kana_openingbracket
0x04a3 」   300D kana_closingbracket
0x04a4 、   3001 kana_comma
0x04a5 ・   30FB kana_conjunctive
0x04a6 ヲ   30F2 kana_WO
0x04a7 ァ   30A1 kana_a
0x04a8 ィ   30A3 kana_i
0x04a9 ゥ   30A5 kana_u
0x04aa ェ   30A7 kana_e
0x04ab ォ   30A9 kana_o
0x04ac ャ   30E3 kana_ya
0x04ad ュ   30E5 kana_yu
0x04ae ョ   30E7 kana_yo
0x04af ッ   30C3 kana_tsu
0x04b0 ー   30FC prolongedsound
0x04b1 ア   30A2 kana_A
0x04b2 イ   30A4 kana_I
0x04b3 ウ   30A6 kana_U
0x04b4 エ   30A8 kana_E
0x04b5 オ   30AA kana_O
0x04b6 カ   30AB kana_KA
0x04b7 キ   30AD kana_KI
0x04b8 ク   30AF kana_KU
0x04b9 ケ   30B1 kana_KE
0x04ba コ   30B3 kana_KO
0x04bb サ   30B5 kana_SA
0x04bc シ   30B7 kana_SHI
0x04bd ス   30B9 kana_SU
0x04be セ   30BB kana_SE
0x04bf ソ   30BD kana_SO
0x04c0 タ   30BF kana_TA
0x04c1 チ   30C1 kana_CHI
0x04c2 ツ   30C4 kana_TSU
0x04c3 テ   30C6 kana_TE
0x04c4 ト   30C8 kana_TO
0x04c5 ナ   30CA kana_NA
0x04c6 ニ   30CB kana_NI
0x04c7 ヌ   30CC kana_NU
0x04c8 ネ   30CD kana_NE
0x04c9 ノ   30CE kana_NO
0x04ca ハ   30CF kana_HA
0x04cb ヒ   30D2 kana_HI
0x04cc フ   30D5 kana_FU
0x04cd ヘ   30D8 kana_HE
0x04ce ホ   30DB kana_HO
0x04cf マ   30DE kana_MA
0x04d0 ミ   30DF kana_MI
0x04d1 ム   30E0 kana_MU
0x04d2 メ   30E1 kana_ME
0x04d3 モ   30E2 kana_MO
0x04d4 ヤ   30E4 kana_YA
0x04d5 ユ   30E6 kana_YU
0x04d6 ヨ   30E8 kana_YO
0x04d7 ラ   30E9 kana_RA
0x04d8 リ   30EA kana_RI
0x04d9 ル   30EB kana_RU
0x04da レ   30EC kana_RE
0x04db ロ   30ED kana_RO
0x04dc ワ   30EF kana_WA
0x04dd ン   30F3 kana_N
0x04de ゛   309B voicedsound
0x04df ゜   309C semivoicedsound
0x05ac ،    060C Arabic_comma
0x05bb ؛    061B Arabic_semicolon
0x05bf ؟    061F Arabic_question_mark
0x05c1 ء    0621 Arabic_hamza
0x05c2 آ    0622 Arabic_maddaonalef
0x05c3 أ    0623 Arabic_hamzaonalef
0x05c4 ؤ    0624 Arabic_hamzaonwaw
0x05c5 إ    0625 Arabic_hamzaunderalef
0x05c6 ئ    0626 Arabic_hamzaonyeh
0x05c7 ا    0627 Arabic_alef
0x05c8 ب    0628 Arabic_beh
0x05c9 ة    0629 Arabic_tehmarbuta
0x05ca ت    062A Arabic_teh
0x05cb ث    062B Arabic_theh
0x05cc ج    062C Arabic_jeem
0x05cd ح    062D Arabic_hah
0x05ce خ    062E Arabic_khah
0x05cf د    062F Arabic_dal
0x05d0 ذ    0630 Arabic_thal
0x05d1 ر    0631 Arabic_ra
0x05d2 ز    0632 Arabic_zain
0x05d3 س    0633 Arabic_seen
0x05d4 ش    0634 Arabic_sheen
0x05d5 ص    0635 Arabic_sad
0x05d6 ض    0636 Arabic_dad
0x05d7 ط    0637 Arabic_tah
0x05d8 ظ    0638 Arabic_zah
0x05d9 ع    0639 Arabic_ain
0x05da غ    063A Arabic_ghain
0x05e0 ـ    0640 Arabic_tatweel
0x05e1 ف    0641 Arabic_feh
0x05e2 ق    0642 Arabic_qaf
0x05e3 ك    0643 Arabic_kaf
0x05e4 ل    0644 Arabic_lam
0x05e5 م    0645 Arabic_meem
0x05e6 ن    0646 Arabic_noon
0x05e7 ه    0647 Arabic_ha
0x05e8 و    0648 Arabic_waw
0x05e9 ى    0649 Arabic_alefmaksura
0x05ea ي    064A Arabic_yeh
0x05eb ◌ً    064B Arabic_fathatan
0x05ec ◌ٌ    064C Arabic_dammatan
0x05ed ◌ٍ    064D Arabic_kasratan
0x05ee ◌َ    064E Arabic_fatha
0x05ef ◌ُ    064F Arabic_damma
0x05f0 ◌ِ    0650 Arabic_kasra
0x05f1 ◌ّ    0651 Arabic_shadda
0x05f2 ◌ْ    0652 Arabic_sukun
0x06a1 ђ    0452 Serbian_dje
0x06a2 ѓ    0453 Macedonia_gje
0x06a3 ё    0451 Cyrillic_io
0x06a4 є    0454 Ukrainian_ie
0x06a5 ѕ    0455 Macedonia_dse
0x06a6 і    0456 Ukrainian_i
0x06a7 ї    0457 Ukrainian_yi
0x06a8 ј    0458 Cyrillic_je
0x06a9 љ    0459 Cyrillic_lje
0x06aa њ    045A Cyrillic_nje
0x06ab ћ    045B Serbian_tshe
0x06ac ќ    045C Macedonia_kje
0x06ad ґ    0491 Ukrainian_ghe_with_upturn
0x06ae ў    045E Byelorussian_shortu
0x06af џ    045F Cyrillic_dzhe
0x06b0 №    2116 numerosign
0x06b1 Ђ    0402 Serbian_DJE
0x06b2 Ѓ    0403 Macedonia_GJE
0x06b3 Ё    0401 Cyrillic_IO
0x06b4 Є    0404 Ukrainian_IE
0x06b5 Ѕ    0405 Macedonia_DSE
0x06b6 І    0406 Ukrainian_I
0x06b7 Ї    0407 Ukrainian_YI
0x06b8 Ј    0408 Cyrillic_JE
0x06b9 Љ    0409 Cyrillic_LJE
0x06ba Њ    040A Cyrillic_NJE
0x06bb Ћ    040B Serbian_TSHE
0x06bc Ќ    040C Macedonia_KJE
0x06bd Ґ    0490 Ukrainian_GHE_WITH_UPTURN
0x06be Ў    040E Byelorussian_SHORTU
0x06bf Џ    040F Cyrillic_DZHE
0x06c0 ю    044E Cyrillic_yu
0x06c1 а    0430 Cyrillic_a
0x06c2 б    0431 Cyrillic_be
0x06c3 ц    0446 Cyrillic_tse
0x06c4 д    0434 Cyrillic_de
0x06c5 е    0435 Cyrillic_ie
0x06c6 ф    0444 Cyrillic_ef
0x06c7 г    0433 Cyrillic_ghe
0x06c8 х    0445 Cyrillic_ha
0x06c9 и    0438 Cyrillic_i
0x06ca й    0439 Cyrillic_shorti
0x06cb к    043A Cyrillic_ka
0x06cc л    043B Cyrillic_el
0x06cd м    043C Cyrillic_em
0x06ce н    043D Cyrillic_en
0x06cf о    043E Cyrillic_o
0x06d0 п    043F Cyrillic_pe
0x06d1 я    044F Cyrillic_ya
0x06d2 р    0440 Cyrillic_er
0x06d3 с    0441 Cyrillic_es
0x06d4 т    0442 Cyrillic_te
0x06d5 у    0443 Cyrillic_u
0x06d6 ж    0436 Cyrillic_zhe
0x06d7 в    0432 Cyrillic_ve
0x06d8 ь    044C Cyrillic_softsign
0x06d9 ы    044B Cyrillic_yeru
0x06da з    0437 Cyrillic_ze
0x06db ш    0448 Cyrillic_sha
0x06dc э    044D Cyrillic_e
0x06dd щ    0449 Cyrillic_shcha
0x06de ч    0447 Cyrillic_che
0x06df ъ    044A Cyrillic_hardsign
0x06e0 Ю    042E Cyrillic_YU
0x06e1 А    0410 Cyrillic_A
0x06e2 Б    0411 Cyrillic_BE
0x06e3 Ц    0426 Cyrillic_TSE
0x06e4 Д    0414 Cyrillic_DE
0x06e5 Е    0415 Cyrillic_IE
0x06e6 Ф    0424 Cyrillic_EF
0x06e7 Г    0413 Cyrillic_GHE
0x06e8 Х    0425 Cyrillic_HA
0x06e9 И    0418 Cyrillic_I
0x06ea Й    0419 Cyrillic_SHORTI
0x06eb К    041A Cyrillic_KA
0x06ec Л    041B Cyrillic_EL
0x06ed М    041C Cyrillic_EM
0x06ee Н    041D Cyrillic_EN
0x06ef О    041E Cyrillic_O
0x06f0 П    041F Cyrillic_PE
0x06f1 Я    042F Cyrillic_YA
0x06f2 Р    0420 Cyrillic_ER
0x06f3 С    0421 Cyrillic_ES
0x06f4 Т    0422 Cyrillic_TE
0x06f5 У    0423 Cyrillic_U
0x06f6 Ж    0416 Cyrillic_ZHE
0x06f7 В    0412 Cyrillic_VE
0x06f8 Ь    042C Cyrillic_SOFTSIGN
0x06f9 Ы    042B Cyrillic_YERU
0x06fa З    0417 Cyrillic_ZE
0x06fb Ш    0428 Cyrillic_SHA
0x06fc Э    042D Cyrillic_E
0x06fd Щ    0429 Cyrillic_SHCHA
0x06fe Ч    0427 Cyrillic_CHE
0x06ff Ъ    042A Cyrillic_HARDSIGN
0x07a1 Ά    0386 Greek_ALPHAaccent
0x07a2 Έ    0388 Greek_EPSILONaccent
0x07a3 Ή    0389 Greek_ETAaccent
0x07a4 Ί    038A Greek_IOTAaccent
0x07a5 Ϊ    03AA Greek_IOTAdieresis
0x07a7 Ό    038C Greek_OMICRONaccent
0x07a8 Ύ    038E Greek_UPSILONaccent
0x07a9 Ϋ    03AB Greek_UPSILONdieresis
0x07ab Ώ    038F Greek_OMEGAaccent
0x07ae ΅    0385 Greek_accentdieresis
0x07af ―    2015 Greek_horizbar
0x07b1 ά    03AC Greek_alphaaccent
0x07b2 έ    03AD Greek_epsilonaccent
0x07b3 ή    03AE Greek_etaaccent
0x07b4 ί    03AF Greek_iotaaccent
0x07b5 ϊ    03CA Greek_iotadieresis
0x07b6 ΐ    0390 Greek_iotaaccentdieresis
0x07b7 ό    03CC Greek_omicronaccent
0x07b8 ύ    03CD Greek_upsilonaccent
0x07b9 ϋ    03CB Greek_upsilondieresis
0x07ba ΰ    03B0 Greek_upsilonaccentdieresis
0x07bb ώ    03CE Greek_omegaaccent
0x07c1 Α    0391 Greek_ALPHA
0x07c2 Β    0392 Greek_BETA
0x07c3 Γ    0393 Greek_GAMMA
0x07c4 Δ    0394 Greek_DELTA
0x07c5 Ε    0395 Greek_EPSILON
0x07c6 Ζ    0396 Greek_ZETA
0x07c7 Η    0397 Greek_ETA
0x07c8 Θ    0398 Greek_THETA
0x07c9 Ι    0399 Greek_IOTA
0x07ca Κ    039A Greek_KAPPA
0x07cb Λ    039B Greek_LAMDA
0x07cc Μ    039C Greek_MU
0x07cd Ν    039D Greek_NU
0x07ce Ξ    039E Greek_XI
0x07cf Ο    039F Greek_OMICRON
0x07d0 Π    03A0 Greek_PI
0x07d1 Ρ    03A1 Greek_RHO
0x07d2 Σ    03A3 Greek_SIGMA
0x07d4 Τ    03A4 Greek_TAU
0x07d5 Υ    03A5 Greek_UPSILON
0x07d6 Φ    03A6 Greek_PHI
0x07d7 Χ    03A7 Greek_CHI
0x07d8 Ψ    03A8 Greek_PSI
0x07d9 Ω    03A9 Greek_OMEGA
0x07e1 α    03B1 Greek_alpha
0x07e2 β    03B2 Greek_beta
0x07e3 γ    03B3 Greek_gamma
0x07e4 δ    03B4 Greek_delta
0x07e5 ε    03B5 Greek_epsilon
0x07e6 ζ    03B6 Greek_zeta
0x07e7 η    03B7 Greek_eta
0x07e8 θ    03B8 Greek_theta
0x07e9 ι    03B9 Greek_iota
0x07ea κ    03BA Greek_kappa
0x07eb λ    03BB Greek_lamda
0x07ec μ    03BC Greek_mu
0x07ed ν    03BD Greek_nu
0x07ee ξ    03BE Greek_xi
0x07ef ο    03BF Greek_omicron
0x07f0 π    03C0 Greek_pi
0x07f1 ρ    03C1 Greek_rho
0x07f2 σ    03C3 Greek_sigma
0x07f3 ς    03C2 Greek_finalsmallsigma
0x07f4 τ    03C4 Greek_tau
0x07f5 υ    03C5 Greek_upsilon
0x07f6 φ    03C6 Greek_phi
0x07f7 χ    03C7 Greek_chi
0x07f8 ψ    03C8 Greek_psi
0x07f9 ω    03C9 Greek_omega
0x08a1 ⎷    23B7 leftradical
0x08a2 ┌    250C topleftradical
0x08a3 ─    2500 horizconnector
0x08a4 ⌠    2320 topintegral
0x08a5 ⌡    2321 botintegral
0x08a6 │    2502 vertconnector
0x08a7 ⎡    23A1 topleftsqbracket
0x08a8 ⎣    23A3 botleftsqbracket
0x08a9 ⎤    23A4 toprightsqbracket
0x08aa ⎦    23A6 botrightsqbracket
0x08ab ⎛    239B topleftparens
0x08ac ⎝    239D botleftparens
0x08ad ⎞    239E toprightparens
0x08ae ⎠    23A0 botrightparens
0x08af ⎨    23A8 leftmiddlecurlybrace
0x08b0 ⎬    23AC rightmiddlecurlybrace
0x08b1 08b1 ---- topleftsummation
0x08b2 08b2 ---- botleftsummation
0x08b3 08b3 ---- topvertsummationconnector
0x08b4 08b4 ---- botvertsummationconnector
0x08b5 08b5 ---- toprightsummation
0x08b6 08b6 ---- botrightsummation
0x08b7 08b7 ---- rightmiddlesummation
0x08bc ≤    2264 lessthanequal
0x08bd ≠    2260 notequal
0x08be ≥    2265 greaterthanequal
0x08bf ∫    222B integral
0x08c0 ∴    2234 therefore
0x08c1 ∝    221D variation
0x08c2 ∞    221E infinity
0x08c5 ∇    2207 nabla
0x08c8 ∼    223C approximate
0x08c9 ≃    2243 similarequal
0x08cd ⇔    21D4 ifonlyif
0x08ce ⇒    21D2 implies
0x08cf ≡    2261 identical
0x08d6 √    221A radical
0x08da ⊂    2282 includedin
0x08db ⊃    2283 includes
0x08dc ∩    2229 intersection
0x08dd ∪    222A union
0x08de ∧    2227 logicaland
0x08df ∨    2228 logicalor
0x08ef ∂    2202 partialderivative
0x08f6 ƒ    0192 function
0x08fb ←    2190 leftarrow
0x08fc ↑    2191 uparrow
0x08fd →    2192 rightarrow
0x08fe ↓    2193 downarrow
0x09df 09df ---- blank
0x09e0 ◆    25C6 soliddiamond
0x09e1 ▒    2592 checkerboard
0x09e2 ␉    2409 ht
0x09e3 ␌    240C ff
0x09e4 ␍    240D cr
0x09e5 ␊    240A lf
0x09e8 ␤    2424 nl
0x09e9 ␋    240B vt
0x09ea ┘    2518 lowrightcorner
0x09eb ┐    2510 uprightcorner
0x09ec ┌    250C upleftcorner
0x09ed └    2514 lowleftcorner
0x09ee ┼    253C crossinglines
0x09ef ⎺    23BA horizlinescan1
0x09f0 ⎻    23BB horizlinescan3
0x09f1 ─    2500 horizlinescan5
0x09f2 ⎼    23BC horizlinescan7
0x09f3 ⎽    23BD horizlinescan9
0x09f4 ├    251C leftt
0x09f5 ┤    2524 rightt
0x09f6 ┴    2534 bott
0x09f7 ┬    252C topt
0x09f8 │    2502 vertbar
0x0aa1 ːem  2003 emspace
0x0aa2 ːen  2002 enspace
0x0aa3 ːem3 2004 em3space
0x0aa4 ːem4 2005 em4space
0x0aa5 ːdig 2007 digitspace
0x0aa6 ːpun 2008 punctspace
0x0aa7 ːthn 2009 thinspace
0x0aa8 ːhai 200A hairspace
0x0aa9 —    2014 emdash
0x0aaa –    2013 endash
0x0aac ␣    2423 signifblank
0x0aae …    2026 ellipsis
0x0aaf ‥    2025 doubbaselinedot
0x0ab0 ⅓    2153 onethird
0x0ab1 ⅔    2154 twothirds
0x0ab2 ⅕    2155 onefifth
0x0ab3 ⅖    2156 twofifths
0x0ab4 ⅗    2157 threefifths
0x0ab5 ⅘    2158 fourfifths
0x0ab6 ⅙    2159 onesixth
0x0ab7 ⅚    215A fivesixths
0x0ab8 ℅    2105 careof
0x0abb ‒    2012 figdash
0x0abc ⟨    27E8 leftanglebracket
0x0abd .    002E decimalpoint
0x0abe ⟩    27E9 rightanglebracket
0x0abf 0abf ---- marker
0x0ac3 ⅛    215B oneeighth
0x0ac4 ⅜    215C threeeighths
0x0ac5 ⅝    215D fiveeighths
0x0ac6 ⅞    215E seveneighths
0x0ac9 ™    2122 trademark
0x0aca ☓    2613 signaturemark
0x0acb 0acb ---- trademarkincircle
0x0acc ◁    25C1 leftopentriangle
0x0acd ▷    25B7 rightopentriangle
0x0ace ○    25CB emopencircle
0x0acf ▯    25AF emopenrectangle
0x0ad0 ‘    2018 leftsinglequotemark
0x0ad1 ’    2019 rightsinglequotemark
0x0ad2 “    201C leftdoublequotemark
0x0ad3 ”    201D rightdoublequotemark
0x0ad4 ℞    211E prescription
0x0ad5 ‰    2030 permille
0x0ad6 ′    2032 minutes
0x0ad7 ″    2033 seconds
0x0ad9 ✝    271D latincross
0x0ada 0ada ---- hexagram
0x0adb ▬    25AC filledrectbullet
0x0adc ◀    25C0 filledlefttribullet
0x0add ▶    25B6 filledrighttribullet
0x0ade ●    25CF emfilledcircle
0x0adf ▮    25AE emfilledrect
0x0ae0 ◦    25E6 enopencircbullet
0x0ae1 ▫    25AB enopensquarebullet
0x0ae2 ▭    25AD openrectbullet
0x0ae3 △    25B3 opentribulletup
0x0ae4 ▽    25BD opentribulletdown
0x0ae5 ☆    2606 openstar
0x0ae6 •    2022 enfilledcircbullet
0x0ae7 ▪    25AA enfilledsqbullet
0x0ae8 ▲    25B2 filledtribulletup
0x0ae9 ▼    25BC filledtribulletdown
0x0aea ☜    261C leftpointer
0x0aeb ☞    261E rightpointer
0x0aec ♣    2663 club
0x0aed ♦    2666 diamond
0x0aee ♥    2665 heart
0x0af0 ✠    2720 maltesecross
0x0af1 †    2020 dagger
0x0af2 ‡    2021 doubledagger
0x0af3 ✓    2713 checkmark
0x0af4 ✗    2717 ballotcross
0x0af5 ♯    266F musicalsharp
0x0af6 ♭    266D musicalflat
0x0af7 ♂    2642 malesymbol
0x0af8 ♀    2640 femalesymbol
0x0af9 ☎    260E telephone
0x0afa ⌕    2315 telephonerecorder
0x0afb ℗    2117 phonographcopyright
0x0afc ‸    2038 caret
0x0afd ‚    201A singlelowquotemark
0x0afe „    201E doublelowquotemark
0x0aff 0aff ---- cursor
0x0ba3 <    003C leftcaret
0x0ba6 >    003E rightcaret
0x0ba8 ∨    2228 downcaret
0x0ba9 ∧    2227 upcaret
0x0bc0 ¯    00AF overbar
0x0bc2 ⊤    22A4 downtack
0x0bc3 ∩    2229 upshoe
0x0bc4 ⌊    230A downstile
0x0bc6 _    005F underbar
0x0bca ∘    2218 jot
0x0bcc ⎕    2395 quad
0x0bce ⊥    22A5 uptack
0x0bcf ○    25CB circle
0x0bd3 ⌈    2308 upstile
0x0bd6 ∪    222A downshoe
0x0bd8 ⊃    2283 rightshoe
0x0bda ⊂    2282 leftshoe
0x0bdc ⊣    22A3 lefttack
0x0bfc ⊢    22A2 righttack
0x0cdf ‗    2017 hebrew_doublelowline
0x0ce0 א    05D0 hebrew_aleph
0x0ce1 ב    05D1 hebrew_bet
0x0ce2 ג    05D2 hebrew_gimel
0x0ce3 ד    05D3 hebrew_dalet
0x0ce4 ה    05D4 hebrew_he
0x0ce5 ו    05D5 hebrew_waw
0x0ce6 ז    05D6 hebrew_zain
0x0ce7 ח    05D7 hebrew_chet
0x0ce8 ט    05D8 hebrew_tet
0x0ce9 י    05D9 hebrew_yod
0x0cea ך    05DA hebrew_finalkaph
0x0ceb כ    05DB hebrew_kaph
0x0cec ל    05DC hebrew_lamed
0x0ced ם    05DD hebrew_finalmem
0x0cee מ    05DE hebrew_mem
0x0cef ן    05DF hebrew_finalnun
0x0cf0 נ    05E0 hebrew_nun
0x0cf1 ס    05E1 hebrew_samech
0x0cf2 ע    05E2 hebrew_ayin
0x0cf3 ף    05E3 hebrew_finalpe
0x0cf4 פ    05E4 hebrew_pe
0x0cf5 ץ    05E5 hebrew_finalzade
0x0cf6 צ    05E6 hebrew_zade
0x0cf7 ק    05E7 hebrew_qoph
0x0cf8 ר    05E8 hebrew_resh
0x0cf9 ש    05E9 hebrew_shin
0x0cfa ת    05EA hebrew_taw
0x0da1 ก    0E01 Thai_kokai
0x0da2 ข    0E02 Thai_khokhai
0x0da3 ฃ    0E03 Thai_khokhuat
0x0da4 ค    0E04 Thai_khokhwai
0x0da5 ฅ    0E05 Thai_khokhon
0x0da6 ฆ    0E06 Thai_khorakhang
0x0da7 ง    0E07 Thai_ngongu
0x0da8 จ    0E08 Thai_chochan
0x0da9 ฉ    0E09 Thai_choching
0x0daa ช    0E0A Thai_chochang
0x0dab ซ    0E0B Thai_soso
0x0dac ฌ    0E0C Thai_chochoe
0x0dad ญ    0E0D Thai_yoying
0x0dae ฎ    0E0E Thai_dochada
0x0daf ฏ    0E0F Thai_topatak
0x0db0 ฐ    0E10 Thai_thothan
0x0db1 ฑ    0E11 Thai_thonangmontho
0x0db2 ฒ    0E12 Thai_thophuthao
0x0db3 ณ    0E13 Thai_nonen
0x0db4 ด    0E14 Thai_dodek
0x0db5 ต    0E15 Thai_totao
0x0db6 ถ    0E16 Thai_thothung
0x0db7 ท    0E17 Thai_thothahan
0x0db8 ธ    0E18 Thai_thothong
0x0db9 น    0E19 Thai_nonu
0x0dba บ    0E1A Thai_bobaimai
0x0dbb ป    0E1B Thai_popla
0x0dbc ผ    0E1C Thai_phophung
0x0dbd ฝ    0E1D Thai_fofa
0x0dbe พ    0E1E Thai_phophan
0x0dbf ฟ    0E1F Thai_fofan
0x0dc0 ภ    0E20 Thai_phosamphao
0x0dc1 ม    0E21 Thai_moma
0x0dc2 ย    0E22 Thai_yoyak
0x0dc3 ร    0E23 Thai_rorua
0x0dc4 ฤ    0E24 Thai_ru
0x0dc5 ล    0E25 Thai_loling
0x0dc6 ฦ    0E26 Thai_lu
0x0dc7 ว    0E27 Thai_wowaen
0x0dc8 ศ    0E28 Thai_sosala
0x0dc9 ษ    0E29 Thai_sorusi
0x0dca ส    0E2A Thai_sosua
0x0dcb ห    0E2B Thai_hohip
0x0dcc ฬ    0E2C Thai_lochula
0x0dcd อ    0E2D Thai_oang
0x0dce ฮ    0E2E Thai_honokhuk
0x0dcf ฯ    0E2F Thai_paiyannoi
0x0dd0 ะ    0E30 Thai_saraa
0x0dd1 ◌ั    0E31 Thai_maihanakat
0x0dd2 า    0E32 Thai_saraaa
0x0dd3 ำ    0E33 Thai_saraam
0x0dd4 ◌ิ    0E34 Thai_sarai
0x0dd5 ◌ี    0E35 Thai_saraii
0x0dd6 ◌ึ    0E36 Thai_saraue
0x0dd7 ◌ื    0E37 Thai_sarauee
0x0dd8 ◌ุ    0E38 Thai_sarau
0x0dd9 ◌ู    0E39 Thai_sarauu
0x0dda ◌ฺ    0E3A Thai_phinthu
0x0dde 0dde ---- Thai_maihanakat_maitho
0x0ddf ฿    0E3F Thai_baht
0x0de0 เ    0E40 Thai_sarae
0x0de1 แ    0E41 Thai_saraae
0x0de2 โ    0E42 Thai_sarao
0x0de3 ใ    0E43 Thai_saraaimaimuan
0x0de4 ไ    0E44 Thai_saraaimaimalai
0x0de5 ๅ    0E45 Thai_lakkhangyao
0x0de6 ๆ    0E46 Thai_maiyamok
0x0de7 ◌็    0E47 Thai_maitaikhu
0x0de8 ◌่    0E48 Thai_maiek
0x0de9 ◌้    0E49 Thai_maitho
0x0dea ◌๊    0E4A Thai_maitri
0x0deb ◌๋    0E4B Thai_maichattawa
0x0dec ◌์    0E4C Thai_thanthakhat
0x0ded ◌ํ    0E4D Thai_nikhahit
0x0df0 ๐    0E50 Thai_leksun
0x0df1 ๑    0E51 Thai_leknung
0x0df2 ๒    0E52 Thai_leksong
0x0df3 ๓    0E53 Thai_leksam
0x0df4 ๔    0E54 Thai_leksi
0x0df5 ๕    0E55 Thai_lekha
0x0df6 ๖    0E56 Thai_lekhok
0x0df7 ๗    0E57 Thai_lekchet
0x0df8 ๘    0E58 Thai_lekpaet
0x0df9 ๙    0E59 Thai_lekkao
0x0ea1 0ea1 ---- Hangul_Kiyeog
0x0ea2 0ea2 ---- Hangul_SsangKiyeog
0x0ea3 0ea3 ---- Hangul_KiyeogSios
0x0ea4 0ea4 ---- Hangul_Nieun
0x0ea5 0ea5 ---- Hangul_NieunJieuj
0x0ea6 0ea6 ---- Hangul_NieunHieuh
0x0ea7 0ea7 ---- Hangul_Dikeud
0x0ea8 0ea8 ---- Hangul_SsangDikeud
0x0ea9 0ea9 ---- Hangul_Rieul
0x0eaa 0eaa ---- Hangul_RieulKiyeog
0x0eab 0eab ---- Hangul_RieulMieum
0x0eac 0eac ---- Hangul_RieulPieub
0x0ead 0ead ---- Hangul_RieulSios
0x0eae 0eae ---- Hangul_RieulTieut
0x0eaf 0eaf ---- Hangul_RieulPhieuf
0x0eb0 0eb0 ---- Hangul_RieulHieuh
0x0eb1 0eb1 ---- Hangul_Mieum
0x0eb2 0eb2 ---- Hangul_Pieub
0x0eb3 0eb3 ---- Hangul_SsangPieub
0x0eb4 0eb4 ---- Hangul_PieubSios
0x0eb5 0eb5 ---- Hangul_Sios
0x0eb6 0eb6 ---- Hangul_SsangSios
0x0eb7 0eb7 ---- Hangul_Ieung
0x0eb8 0eb8 ---- Hangul_Jieuj
0x0eb9 0eb9 ---- Hangul_SsangJieuj
0x0eba 0eba ---- Hangul_Cieuc
0x0ebb 0ebb ---- Hangul_Khieuq
0x0ebc 0ebc ---- Hangul_Tieut
0x0ebd 0ebd ---- Hangul_Phieuf
0x0ebe 0ebe ---- Hangul_Hieuh
0x0ebf 0ebf ---- Hangul_A
0x0ec0 0ec0 ---- Hangul_AE
0x0ec1 0ec1 ---- Hangul_YA
0x0ec2 0ec2 ---- Hangul_YAE
0x0ec3 0ec3 ---- Hangul_EO
0x0ec4 0ec4 ---- Hangul_E
0x0ec5 0ec5 ---- Hangul_YEO
0x0ec6 0ec6 ---- Hangul_YE
0x0ec7 0ec7 ---- Hangul_O
0x0ec8 0ec8 ---- Hangul_WA
0x0ec9 0ec9 ---- Hangul_WAE
0x0eca 0eca ---- Hangul_OE
0x0ecb 0ecb ---- Hangul_YO
0x0ecc 0ecc ---- Hangul_U
0x0ecd 0ecd ---- Hangul_WEO
0x0ece 0ece ---- Hangul_WE
0x0ecf 0ecf ---- Hangul_WI
0x0ed0 0ed0 ---- Hangul_YU
0x0ed1 0ed1 ---- Hangul_EU
0x0ed2 0ed2 ---- Hangul_YI
0x0ed3 0ed3 ---- Hangul_I
0x0ed4 0ed4 ---- Hangul_J_Kiyeog
0x0ed5 0ed5 ---- Hangul_J_SsangKiyeog
0x0ed6 0ed6 ---- Hangul_J_KiyeogSios
0x0ed7 0ed7 ---- Hangul_J_Nieun
0x0ed8 0ed8 ---- Hangul_J_NieunJieuj
0x0ed9 0ed9 ---- Hangul_J_NieunHieuh
0x0eda 0eda ---- Hangul_J_Dikeud
0x0edb 0edb ---- Hangul_J_Rieul
0x0edc 0edc ---- Hangul_J_RieulKiyeog
0x0edd 0edd ---- Hangul_J_RieulMieum
0x0ede 0ede ---- Hangul_J_RieulPieub
0x0edf 0edf ---- Hangul_J_RieulSios
0x0ee0 0ee0 ---- Hangul_J_RieulTieut
0x0ee1 0ee1 ---- Hangul_J_RieulPhieuf
0x0ee2 0ee2 ---- Hangul_J_RieulHieuh
0x0ee3 0ee3 ---- Hangul_J_Mieum
0x0ee4 0ee4 ---- Hangul_J_Pieub
0x0ee5 0ee5 ---- Hangul_J_PieubSios
0x0ee6 0ee6 ---- Hangul_J_Sios
0x0ee7 0ee7 ---- Hangul_J_SsangSios
0x0ee8 0ee8 ---- Hangul_J_Ieung
0x0ee9 0ee9 ---- Hangul_J_Jieuj
0x0eea 0eea ---- Hangul_J_Cieuc
0x0eeb 0eeb ---- Hangul_J_Khieuq
0x0eec 0eec ---- Hangul_J_Tieut
0x0eed 0eed ---- Hangul_J_Phieuf
0x0eee 0eee ---- Hangul_J_Hieuh
0x0eef 0eef ---- Hangul_RieulYeorinHieuh
0x0ef0 0ef0 ---- Hangul_SunkyeongeumMieum
0x0ef1 0ef1 ---- Hangul_SunkyeongeumPieub
0x0ef2 0ef2 ---- Hangul_PanSios
0x0ef3 0ef3 ---- Hangul_KkogjiDalrinIeung
0x0ef4 0ef4 ---- Hangul_SunkyeongeumPhieuf
0x0ef5 0ef5 ---- Hangul_YeorinHieuh
0x0ef6 0ef6 ---- Hangul_AraeA
0x0ef7 0ef7 ---- Hangul_AraeAE
0x0ef8 0ef8 ---- Hangul_J_PanSios
0x0ef9 0ef9 ---- Hangul_J_KkogjiDalrinIeung
0x0efa 0efa ---- Hangul_J_YeorinHieuh
0x0eff ₩    20A9 Korean_Won
0x13bc Œ    0152 OE
0x13bd œ    0153 oe
0x13be Ÿ    0178 Ydiaeresis
0x20ac €    20AC EuroSign
0xfe01 gLck ---- ISO_Lock
0xfe02 g11. ---- ISO_Level2_Latch
0xfe03 g3-  ---- ISO_Level3_Shift ⓷▝
0xfe04 g3.  ---- ISO_Level3_Latch ⓷ 
0xfe05 g3^  ---- ISO_Level3_Lock
0xfe06 Ms.  ---- ISO_Group_Latch
0xfe07 LX^  ---- ISO_Group_Lock
0xfe08 LN.  ---- ISO_Next_Group
0xfe09 fe09 ---- ISO_Next_Group_Lock
0xfe0a LPre ---- ISO_Prev_Group
0xfe0b fe0b ---- ISO_Prev_Group_Lock
0xfe0c LFst ---- ISO_First_Group
0xfe0d fe0d ---- ISO_First_Group_Lock
0xfe0e LLas ---- ISO_Last_Group
0xfe0f fe0f ---- ISO_Last_Group_Lock
0xfe11 g5-  ---- ISO_Level5_Shift ⓹▝
0xfe12 g5.  ---- ISO_Level5_Latch ⓹
0xfe13 g5^  ---- ISO_Level5_Lock
0xfe20 TabL ---- ISO_Left_Tab %u⟽
0xfe21 fe21 ---- ISO_Move_Line_Up
0xfe22 fe22 ---- ISO_Move_Line_Down
0xfe23 fe23 ---- ISO_Partial_Line_Up
0xfe24 fe24 ---- ISO_Partial_Line_Down
0xfe25 fe25 ---- ISO_Partial_Space_Left
0xfe26 fe26 ---- ISO_Partial_Space_Right
0xfe27 fe27 ---- ISO_Set_Margin_Left
0xfe28 fe28 ---- ISO_Set_Margin_Right
0xfe29 fe29 ---- ISO_Release_Margin_Left
0xfe2a fe2a ---- ISO_Release_Margin_Right
0xfe2b fe2b ---- ISO_Release_Both_Margins
0xfe2c fe2c ---- ISO_Fast_Cursor_Left
0xfe2d fe2d ---- ISO_Fast_Cursor_Right
0xfe2e fe2e ---- ISO_Fast_Cursor_Up
0xfe2f fe2f ---- ISO_Fast_Cursor_Down
0xfe30 fe30 ---- ISO_Continuous_Underline
0xfe31 fe31 ---- ISO_Discontinuous_Underline
0xfe32 fe32 ---- ISO_Emphasize
0xfe33 fe33 ---- ISO_Center_Object
0xfe34 IEnt ---- ISO_Enter
0xfe50 .à   ---- dead_grave
0xfe51 .á   ---- dead_acute
0xfe52 .â   ---- dead_circumflex
0xfe53 .ã   ---- dead_tilde
0xfe54 .ā   ---- dead_macron
0xfe55 .ă   ---- dead_breve
0xfe56 .ċ   ---- dead_abovedot
0xfe57 .ä   ---- dead_diaeresis
0xfe58 .å   ---- dead_abovering
0xfe59 .ő   ---- dead_doubleacute
0xfe5a .č   ---- dead_caron
0xfe5b .ç   ---- dead_cedilla
0xfe5c .ą   ---- dead_ogonek
0xfe5d .ɩ   ---- dead_iota
0xfe5e .v   ---- dead_voiced_sound
0xfe5f .˅   ---- dead_semivoiced_sound
0xfe60 .ḅ   ---- dead_belowdot
0xfe61 .ƈ   ---- dead_hook
0xfe62 .ơ   ---- dead_horn
0xfe63 .ø   ---- dead_stroke
0xfe64 .’   ---- dead_abovecomma
0xfe65 .‘   ---- dead_abovereversedcomma
0xfe66 .ȁ   ---- dead_doublegrave
0xfe67 .ḁ   ---- dead_belowring
0xfe68 .ḇ   ---- dead_belowmacron
0xfe69 .ḓ   ---- dead_belowcircumflex
0xfe6a .ḛ   ---- dead_belowtilde
0xfe6b .ḫ   ---- dead_belowbreve
0xfe6c .ṳ   ---- dead_belowdiaeresis
0xfe6d .ȃ   ---- dead_invertedbreve
0xfe6e .ș   ---- dead_belowcomma
0xfe6f .¤   ---- dead_currency
0xfe8a .ə   ---- dead_small_schwa
0xfe8b .Ə   ---- dead_capital_schwa
0xfe8c .Ɛ   ---- dead_greek
0xfe90 ._   ---- dead_lowline
0xfe91 .˥   ---- dead_aboveverticalline
0xfe92 .˩   ---- dead_belowverticalline
0xfe93 ./   ---- dead_longsolidusoverlay
0xfe70 fe70 ---- AccessX_Enable
0xfe71 fe71 ---- AccessX_Feedback_Enable
0xfe72 fe72 ---- RepeatKeys_Enable
0xfe73 fe73 ---- SlowKeys_Enable
0xfe74 fe74 ---- BounceKeys_Enable
0xfe75 fe75 ---- StickyKeys_Enable
0xfe76 fe76 ---- MouseKeys_Enable
0xfe77 fe77 ---- MouseKeys_Accel_Enable
0xfe78 Ov1  ---- Overlay1_Enable
0xfe79 Ov2  ---- Overlay2_Enable
0xfe7a fe7a ---- AudibleBell_Enable
0xfe80 fe80 ---- dead_a
0xfe81 fe81 ---- dead_A
0xfe82 fe82 ---- dead_e
0xfe83 fe83 ---- dead_E
0xfe84 fe84 ---- dead_i
0xfe85 fe85 ---- dead_I
0xfe86 fe86 ---- dead_o
0xfe87 fe87 ---- dead_O
0xfe88 fe88 ---- dead_u
0xfe89 fe89 ---- dead_U
0xfea0 fea0 ---- ch
0xfea1 fea1 ---- Ch
0xfea2 fea2 ---- CH
0xfea3 fea3 ---- c_h
0xfea4 fea4 ---- C_h
0xfea5 fea5 ---- C_H
0xfed0 X⇱   ---- First_Virtual_Screen
0xfed1 X⇐   ---- Prev_Virtual_Screen
0xfed2 X⇒   ---- Next_Virtual_Screen
0xfed4 X⇲   ---- Last_Virtual_Screen
0xfed5 Xkil ---- Terminate_Server
0xfee0 fee0 ---- Pointer_⓹̲eft
0xfee1 fee1 ---- Pointer_Right
0xfee2 fee2 ---- Pointer_Up
0xfee3 fee3 ---- Pointer_Down
0xfee4 fee4 ---- Pointer_UpLeft
0xfee5 fee5 ---- Pointer_UpRight
0xfee6 fee6 ---- Pointer_DownLeft
0xfee7 fee7 ---- Pointer_DownRight
0xfee8 fee8 ---- Pointer_Button_Dflt
0xfee9 fee9 ---- Pointer_Button1
0xfeea feea ---- Pointer_Button2
0xfeeb feeb ---- Pointer_Button3
0xfeec feec ---- Pointer_Button4
0xfeed feed ---- Pointer_Button5
0xfeee feee ---- Pointer_DblClick_Dflt
0xfeef feef ---- Pointer_DblClick1
0xfef0 fef0 ---- Pointer_DblClick2
0xfef1 fef1 ---- Pointer_DblClick3
0xfef2 fef2 ---- Pointer_DblClick4
0xfef3 fef3 ---- Pointer_DblClick5
0xfef4 fef4 ---- Pointer_Drag_Dflt
0xfef5 fef5 ---- Pointer_Drag1
0xfef6 fef6 ---- Pointer_Drag2
0xfef7 fef7 ---- Pointer_Drag3
0xfef8 fef8 ---- Pointer_Drag4
0xfef9 fef9 ---- Pointer_EnableKeys
0xfefa fefa ---- Pointer_Accelerate
0xfefb fefb ---- Pointer_DfltBtnNext
0xfefc fefc ---- Pointer_DfltBtnPrev
0xfefd fefd ---- Pointer_Drag5
0xff08 Bksp ---- BackSpace %u⌫
0xff09 Tab  ---- Tab %u⟾
0xff0a Lf   ---- Linefeed
0xff0b Clr  ---- Clear
0xff0d Ret  ---- Return
0xff13 Pau  ---- Pause
0xff14 Sclk ---- Scroll_Lock
0xff15 Sreq ---- Sys_Req
0xff1b Esc  ---- Escape %wEˢ᷐
0xff20 Comp ---- Multi_key
0xff21 ff21 ---- Kanji
0xff22 ff22 ---- Muhenkan
0xff23 ff23 ---- Henkan_Mode
0xff24 ff24 ---- Romaji
0xff25 ff25 ---- Hiragana
0xff26 ff26 ---- Katakana
0xff27 ff27 ---- Hiragana_Katakana
0xff28 ff28 ---- Zenkaku
0xff29 ff29 ---- Hankaku
0xff2a ff2a ---- Zenkaku_Hankaku
0xff2b ff2b ---- Touroku
0xff2c ff2c ---- Massyo
0xff2d ff2d ---- Kana_Lock
0xff2e ff2e ---- Kana_Shift
0xff2f ff2f ---- Eisu_Shift
0xff30 ff30 ---- Eisu_toggle
0xff31 ff31 ---- Hangul
0xff32 ff32 ---- Hangul_Start
0xff33 ff33 ---- Hangul_End
0xff34 ff34 ---- Hangul_Hanja
0xff35 ff35 ---- Hangul_Jamo
0xff36 ff36 ---- Hangul_Romaja
0xff37 ff37 ---- Codeinput
0xff38 ff38 ---- Hangul_Jeonja
0xff39 ff39 ---- Hangul_Banja
0xff3a ff3a ---- Hangul_PreHanja
0xff3b ff3b ---- Hangul_PostHanja
0xff3c ff3c ---- SingleCandidate
0xff3d ff3d ---- MultipleCandidate
0xff3e ff3e ---- PreviousCandidate
0xff3f ff3f ---- Hangul_Special
0xff50 Home ---- Home  %s⬉
0xff51 Left ---- Left  %s◀
0xff52 Up   ---- Up    %s▲
0xff53 Rght ---- Right %s▶ 
0xff54 Down ---- Down  %s▼
0xff55 PgUp ---- Prior %s▀
0xff56 PgDn ---- Next  %s▄
0xff57 End  ---- End   %s⬊
0xff58 Beg  ---- Begin
0xff60 Sel  ---- Select
0xff61 Prc  ---- Print
0xff62 Exe  ---- Execute
 0xff63 Ins  ---- Insert %wIₛᷡ
0xff63 Ins  ---- Insert ⌂⃜
 0xff63 Ins  ---- Insert  ⌤
0xff65 Undo ---- Undo
0xff66 Redo ---- Redo
0xff67 Menu ---- Menu
0xff68 Find ---- Find
0xff69 Canc ---- Cancel
0xff6a Help ---- Help
0xff6b Brk  ---- Break
0xff7e g9   ---- Mode_switch ⓽▝ 
0xff7f NmLk ---- Num_Lock
0xff80 #_   ---- KP_Space
0xff89 #Tab ---- KP_Tab %u⟾
0xff8d #Ret ---- KP_Enter
0xff91 #F1  ---- KP_F1
0xff92 #F2  ---- KP_F2
0xff93 #F3  ---- KP_F3
0xff94 #F4  ---- KP_F4
0xff95 #Hom ---- KP_Home   %s⬉
0xff96 #Lft ---- KP_Left   %s◀
0xff97 #Up  ---- KP_Up     %s▲
0xff98 #Rt  ---- KP_Right  %s▶
0xff99 #Dn  ---- KP_Down   %s▼
0xff9a #Pup ---- KP_Prior  %s▀
0xff9b #Pdn ---- KP_Next   %s▄
0xff9c #End ---- KP_End    %s⬊
0xff9d #Beg ---- KP_Begin
0xff9e #Ins ---- KP_Insert %wIₛᷡ
0xff9f #Del ---- KP_Delete %u⌧
0xffaa #*   ---- KP_Multiply
0xffab #+   ---- KP_Add
0xffac #,   ---- KP_Separator
0xffad #-   ---- KP_Subtract
0xffae #.   ---- KP_Decimal
0xffaf #/   ---- KP_Divide
0xffb0 #0   ---- KP_0
0xffb1 #1   ---- KP_1
0xffb2 #2   ---- KP_2
0xffb3 #3   ---- KP_3
0xffb4 #4   ---- KP_4
0xffb5 #5   ---- KP_5
0xffb6 #6   ---- KP_6
0xffb7 #7   ---- KP_7
0xffb8 #8   ---- KP_8
0xffb9 #9   ---- KP_9
0xffbd #==  ---- KP_Equal
0xffbe F1   ---- F1
0xffbf F2   ---- F2
0xffc0 F3   ---- F3
0xffc1 F4   ---- F4
0xffc2 F5   ---- F5
0xffc3 F6   ---- F6
0xffc4 F7   ---- F7
0xffc5 F8   ---- F8
0xffc6 F9   ---- F9
0xffc7 F10  ---- F10
0xffc8 F11  ---- F11
0xffc9 F12  ---- F12
0xffca F13  ---- F13
0xffcb F14  ---- F14
0xffcc F15  ---- F15
0xffcd F16  ---- F16
0xffce F17  ---- F17
0xffcf F18  ---- F18
0xffd0 F19  ---- F19
0xffd1 F20  ---- F20
0xffd2 F21  ---- F21
0xffd3 F22  ---- F22
0xffd4 F23  ---- F23
0xffd5 F24  ---- F24
0xffd6 ffd6 ---- F25
0xffd7 ffd7 ---- F26
0xffd8 ffd8 ---- F27
0xffd9 ffd9 ---- F28
0xffda ffda ---- F29
0xffdb ffdb ---- F30
0xffdc ffdc ---- F31
0xffdd ffdd ---- F32
0xffde ffde ---- F33
0xffdf ffdf ---- F34
0xffe0 ffe0 ---- F35
0xffe1 LSh  ---- Shift_L
0xffe2 RSh  ---- Shift_R
0xffe3 LCtl ---- Control_L
0xffe4 RCtl ---- Control_R
0xffe5 CLck ---- Caps_Lock
0xffe6 SLck ---- Shift_Lock
0xffe7 LMet ---- Meta_L
0xffe8 RMet ---- Meta_R
0xffe9 LAlt ---- Alt_L
0xffea RAlt ---- Alt_R
0xffeb LSup ---- Super_L
0xffec RSup ---- Super_R
0xffed LHyp ---- Hyper_L
0xffee RHyp ---- Hyper_R
0xfff1 fff1 ---- braille_dot_1
0xfff2 fff2 ---- braille_dot_2
0xfff3 fff3 ---- braille_dot_3
0xfff4 fff4 ---- braille_dot_4
0xfff5 fff5 ---- braille_dot_5
0xfff6 fff6 ---- braille_dot_6
0xfff7 fff7 ---- braille_dot_7
0xfff8 fff8 ---- braille_dot_8
0xfff9 fff9 ---- braille_dot_9
0xfffa fffa ---- braille_dot_10
0xffff Del  ---- Delete %u⌧
:U:uni: "special" unicode. Eg. invisibles
0x100feff ZNBS FEFF ⌶nbs 
0x100202f NNBS 202F ːnnb
0x100205f MMSP 205F ːmma
0x1002028 LSEP 2028 Line_Separator
0x1002029 PSEP 2029 Paragraph_Separator
0x100200b ZWSP 200B ⌶sp 
0x100200c ZWNJ 200C ⌶nj 
0x100200d ZWJ  200D ⌶j  
0x100034f CGJ  034F ⌶cgj
0x1002060 ZWWJ 2060 ⌶wj 
0x1002061 EFUA 2061 ⌶fua
0x1002062 EITI 2062 ⌶iti
0x1002063 EICO 2063 ⌶ico
0x1002064 EIAD 2064 ⌶iad
0x100202a ELRE 202A ⌶lre
0x100202b ERLE 202B ⌶rle
0x100202c EPDF 202C ⌶pdf
0x100202d ELRO 202D ⌶lro
0x100202e ERLO 202E ⌶rlo
